Updating the regex to accept multiple semi colon parsing. Added tests…
zacharyrankin/wordhi pull request #3
Opened 2016-09-19 23:47 UTC by robdog

… to support new functionality.

2016-09-20 03:21 UTC, zacharyrankin commented on src/Tokenizer.php
> +            "/^&[^\s;]*;/"              => ['type' => 'html-entity', 'value_fn' => $returnMatches],
I would fix your spacing here 😄

2016-09-20 03:21 UTC, zacharymarshal requested changes
Looks good.

2016-09-20 22:36 UTC, robdog commented on src/Tokenizer.php
> +            "/^&[^\s;]*;/"              => ['type' => 'html-entity', 'value_fn' => $returnMatches],
This is fixed now! Approves it sir!!@#!@

2016-09-23 15:03 UTC, zacharyrankin commented
Haha all good now. Merge it! 📽

2016-09-26 21:13 UTC, merged